### ISSUE TITLE
label doesn't update with volume change

### ISSUE THREAD

**Issue by grenzionky** [marioortizmanero/polybar-pulseaudio-control#1]
scrolling on the thing and clicking does change and mute the volume, but the actual label text doesnt change until i restart polybar

**Comment by marioortizmanero** [comment]
Are you using the same module (or a fairly similar one) as the one from the README? Can you show me an example of whatever `pactl subscribe` outputs when you modify the volume? It should be something like:

```
Event 'change' on sink #1
Event 'remove' on client #189
```

The script detects `on card`, `on remove` or `on server` from `pactl subscribe` to update the label so it might not be recognizing the updates.

**Comment by marioortizmanero** [comment]
Closing issue as it's inactive.
