### ISSUE TITLE
Error flash on volume level change

### ISSUE THREAD

**Issue by yigitsever** [marioortizmanero/polybar-pulseaudio-control#4]
Changing the volume causes the module to flash with the error message

`./pulseaudio-control.sh: line 189: [: too many arguments`

Similar result can be achieved by simply running the script from the command line;

```
δ ./pulseaudio-control.sh --listen
./pulseaudio-control.sh: line 189: [: too many arguments
# 75%   # 2                                                    
```

**Comment by marioortizmanero** [comment]
What's your output of `pgrep pulseaudio`?

I think your `pgrep` is returning something different than just the process ID. Which should be easy to fix by adding `"` in the line 189.

**Comment by yigitsever** [comment]
805
6157
6168

I've fixed the issue by quoting, sending the fix now

**Comment by marioortizmanero** [comment]
That's it then. Thanks a bunch for your help!
