### ISSUE TITLE
next-sink ignores one device using PipeWire

### ISSUE THREAD

**Issue by valters-tomsons** [marioortizmanero/polybar-pulseaudio-control#50]
Hi!

When switching to PipeWire, it seems that one of my devices get ignored when switching sinks with `next-sink`. If I set the sink manually with `pactl set-default-sink %`, it gets correctly identified and shows the correct nickname in `listen` mode.

Here is output of `pacmd list sinks`: https://gist.github.com/valters-tomsons/531a321164904aed3d2ae9ef6b1c091b
The device in question: `ATH-G1WL Analog Stereo`

**Comment by marioortizmanero** [comment]
Ahhh I was experiencing the same bug haha. Turns out the sinks are not printed in order, so it's stuck at the first one. I have to sort the sink indexes in `nextSink` and it should work. Give me a couple mins.

**Comment by marioortizmanero** [comment]
This should work with v2.2.2 now!

**Comment by valters-tomsons** [comment]
It does work!
