### ISSUE TITLE
Next to % of volume says Sink #0

### ISSUE THREAD

**Issue by 92naMoN** [marioortizmanero/polybar-pulseaudio-control#51]
Hi, i have been using your script for volume control and everything works fine, but next to % of volume it says Sink #0. I have tried to remove it with some flags ( for example --autosync) but it didn`t work. It is small thing and i am sure that it is only for me but it is a bit annoying. 

If you could help it would be much appreciated!
 
![volumecontrolscript](https://user-images.githubusercontent.com/79383086/122633151-48a12b00-d0d7-11eb-90d3-b172f0966c16.png)
![ps](https://user-images.githubusercontent.com/79383086/122633156-4d65df00-d0d7-11eb-8834-e2a3a4c6b3dc.png)

**Comment by marioortizmanero** [comment]
That's just the currently active sink (say, your speakers or headphones). You can disable it with a custom format: `--format '$VOL_ICON ${VOL_LEVEL}%'` (in the `exec` field), or you can customize it to show something else via nicknames. Check out the Readme for more.
