### ISSUE TITLE
--sink-nickname works for <name> but not for <nick>

### ISSUE THREAD

**Issue by MarkGotLasagna** [marioortizmanero/polybar-pulseaudio-control#61]
Steps to reproduce:

1. copy paste default configuration for `exec` found inside README (here tweaked, it makes no difference) 
```
exec = pulseaudio-control --icons-volume " , , " --icon-muted "" --sink-nicknames-from "device.description" 
--sink-nickname "alsa_output.pci-0000_00_1b.0.analog-stereo: speaker" 
--sink-nickname "alsa_output.usb-Kingston_HyperX_Virtual_Surround_Sound_00000000-00.analog-stereo" listen
```
2. reload i3 with `Mod + Shift + R`

Expected behavior:

- shows icon and text as supposed to (see `--sink-nickname <name>:<nick>` in `pavu-control --help`

What does **NOT** happen is the module displaying the nickname and icon I gave for the sink
![image](https://user-images.githubusercontent.com/59115463/170121191-6bdee71f-2535-4f7c-9b3d-0d5354d8ea0a.png)
```
[module/pulseaudio-control]
type = custom/script
tail = true
format-underline = #0000FF
label-foreground = ${colors.foreground}
;label-maxlen = 30

# Icons mixed from Font Awesome 5 and Material Icons
# You can copy-paste your options for each possible action, which is more
# trouble-free but repetitive, or apply only the relevant ones (for example
# --sink-blacklist is only needed for next-sink).
exec = pulseaudio-control --icons-volume " , , " --icon-muted "" --sink-nicknames-from "device.description" 
--sink-nickname "alsa_output.pci-0000_00_1b.0.analog-stereo: speaker" 
--sink-nickname "alsa_output.usb-Kingston_HyperX_Virtual_Surround_Sound_00000000-00.analog-stereo" listen
click-right = pulseaudio-control --sink-blacklist "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra2" next-sink
```

Am I doing something wrong?
using arch linux
i3 as wm
picom as compositor

**Comment by MarkGotLasagna** [comment]
Found out that I'm stupid nvm
Use the command `pactl list sinks | grep Name` to list YOUR devices and change the ones inside the config accordingly
e.g.
> `--sink-nickname "alsa_output.usb-Astro_Gaming_Astro_A50-00.stereo-game: Astro A50"`

**Comment by marioortizmanero** [comment]
No problem! If you have any other problems do let me know.
