### ISSUE TITLE
Small issue and easyeffects

### ISSUE THREAD

**Issue by GreenFishy** [marioortizmanero/polybar-pulseaudio-control#62]
Hi! 
I have a small issue where, I run pactl I receive this:
![ppc](https://user-images.githubusercontent.com/106456764/171057719-d79e60af-4c0e-4b76-83ba-e862a9f48f28.png)
(I checked to see if there was a difference when I had headphones plugged in and the result was the same. i.e pactl list sinks | grep Name from issue #61 the listed sinks remain the same output)
I have tried changing the --sink-name to either one to see if it change anything but nothings working at this point and I have 0 experience with pulse/pipewire/easyeffects any sound related thing.
![ppc2](https://user-images.githubusercontent.com/106456764/171058873-248f473d-0d1a-4a7f-9964-50851a722528.png)

system:
endeavouros
i3wm
any help is appreciated thanks!

**Comment by marioortizmanero** [comment]
You probably have to consider the port. Do `pactl list sinks` without the `grep` and see what value `Ports` have. You can specify them in this script with `name/port`. On my machine:

```
	Ports:
		analog-output-speaker: Speakers (type: Speaker, priority: 10000, availability group: Legacy 3, availability unknown)
		analog-output-headphones: Headphones (type: Headphones, priority: 9900, availability group: Legacy 2, not available)
	Active Port: analog-output-speaker
```

**Comment by marioortizmanero** [comment]
Closing this for now, let me know if didn't manage to fix it and I will reopen.
