### ISSUE TITLE
How can I hide output and input devices name?

### ISSUE THREAD

**Issue by zukrmn** [marioortizmanero/polybar-pulseaudio-control#73]
I used your example screenshot module:

![image](https://user-images.githubusercontent.com/105821940/195962962-127d09a4-ef06-475f-88d3-efca17035db0.png)

**Comment by EclipzzeX** [comment]
`--sink-nickname "alsa_output.usb-Synaptics_USB-A_to_3.5mm_Jack_Audio_Adapter_0000000000000000-00.analog-stereo:  Headphones" `
My device is in the double quotes up to the colon : then is my icon (does not show here) and then the name I want to show in my bar 

![image](https://user-images.githubusercontent.com/22237366/205156929-8cd6d031-6982-4458-b329-49f7cf9a7bd5.png)

**Comment by marioortizmanero** [comment]
Hi, sorry for the late response. You can either use a nickname or a custom `FORMAT` to remove it completely.
