### ISSUE TITLE
Notifications for all changes in PA

### ISSUE THREAD

**Issue by root2185** [marioortizmanero/polybar-pulseaudio-control#76]
Like pasystray https://github.com/christophgysin/pasystray.
Currently can you enable them just for node changes?

**Comment by marioortizmanero** [comment]
Not sure if that's within the scope of this script, we only have notifications for the events you create yourself (e.g., changing the sink). It'd be confusing to have both, in my opinion. Regardless, if you really wanted that, you could edit the script yourself. We receive all the new events in the `listen` function, so you could add a `notify-send` in there, though it'll be noisy, as we have some duplicate events sometimes.
